export const COUNTRIES = [
    { name: 'Argentina', code: 'ar' },
    { name: 'Australia', code: 'au' },
    { name: 'Austria', code: 'at' },
    { name: 'Belgium', code: 'be' },
    { name: 'Brazil', code: 'br' },
    { name: 'Bulgaria', code: 'bg' },
    { name: 'Canada', code: 'ca' },
    { name: 'China', code: 'cn' },
    { name: 'Colombia', code: 'CO' },
    { name: 'Cuba', code: 'cu' },
    { name: 'Czech Republic', code: 'cz' },
    { name: 'Egypt', code: 'eg' },
    { name: 'France', code: 'fr' },
    { name: 'Greece', code: 'gr' },
    { name: 'Hong Kong', code: 'hk' },
    { name: 'Hungary', code: 'hu' },
    { name: 'India', code: 'in' },
    { name: 'Indonesia', code: 'id' },
    { name: 'Ireland', code: 'ie' },
    { name: 'Israel', code: 'il' },
    { name: 'Italy', code: 'it' },
    { name: 'Japan', code: 'jp' },
    { name: 'Latvia', code: 'lv' },
    { name: 'Lithuania', code: 'lt' },
    { name: 'Malaysia', code: 'my' },
    { name: 'Mexico', code: 'mx' },
    { name: 'Morocco', code: 'ma' },
    { name: 'Namibia', code: 'NA' },
    { name: 'Netherlands', code: 'nl' },
    { name: 'New Zealand', code: 'nz' },
    { name: 'Nigeria', code: 'ng' },
    { name: 'Norway', code: 'no' },
    { name: 'Philippines', code: 'ph' },
    { name: 'Poland', code: 'pl' },
    { name: 'Portugal', code: 'pt' },
    { name: 'Romania', code: 'ro' },
    { name: 'Russia', code: 'ru' },
    { name: 'Saudi Arabia', code: 'sa' },
    { name: 'Serbia and Montenegro', code: 'cs' },
    { name: 'Singapore', code: 'sg' },
    { name: 'Slovakia', code: 'sk' },
    { name: 'Slovenia', code: 'si' },
    { name: 'South Africa', code: 'za' },
    { name: 'Sweden', code: 'se' },
    { name: 'Switzerland', code: 'ch' },
    { name: 'Taiwan', code: 'tw' },
    { name: 'Thailand', code: 'th' },
    { name: 'Turkey', code: 'tr' },
    { name: 'Ukraine', code: 'UA' },
    { name: 'United Arab Emirates', code: 'AE' },
    { name: 'United Kingdom', code: 'GB' },
    { name: 'United States', code: 'US' }
  ];